<?php
namespace Icecave\Manifold\Authentication\Caching;

use Icecave\Manifold\Authentication\StaticCredentialsProviderInterface;

/**
 * The interface implemented by credentials provider cache generators.
 */
interface CredentialsCacheGeneratorInterface
{
    /**
     * Generate PHP code to recreate the supplied credentials provider.
     *
     * The code generated by this method is intended to be stored in a file that
     * will be cached by the PHP opcode cache, effectively bypassing the need to
     * validate the credentials file each time.
     *
     * @param StaticCredentialsProviderInterface $provider The credentials provider to generate code for.
     *
     * @return string PHP source code that will replicate the supplied credentials provider.
     */
    public function generate(StaticCredentialsProviderInterface $provider);
}
