<?php
namespace Icecave\Manifold\Configuration\Caching;

use Icecave\Manifold\Configuration\ConfigurationInterface;

/**
 * The interface implemented by configuration cache generators.
 */
interface ConfigurationCacheGeneratorInterface
{
    /**
     * Generate PHP code to recreate the supplied configuration.
     *
     * The code generated by this method is intended to be stored in a file that
     * will be cached by the PHP opcode cache, effectively bypassing the need to
     * validate the configuration file each time.
     *
     * @param ConfigurationInterface $configuration The configuration to generate code for.
     *
     * @return string PHP source code that will replicate the supplied configuration.
     */
    public function generate(ConfigurationInterface $configuration);
}
