language: php

php: ["5.3", "5.4", "5.5"]

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "vlNpYMTVluF0sXh/pQRtWZYrTxnpHlM0nuu4G/QaALrHkSjpdAJDJVACyCha/rnnpNWtYwFs42nGAlq9cc4NEK/HGiiRzSyonbeBQ9Y+BouxghCB9MkQv0MFLIhnFXuFxgJ9rn/PhcNGddhmwAov7Upc+JQkHo095fuJk3vENK4="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
